root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/lamba main.go"
bin = "tmp/lamba"
full_bin = "./tmp/lamba"
include_ext = ["go", "tpl", "tmpl", "html", "so"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"