version: 1

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
      {{ if ne .Os "windows" }}.tar.gz{{ else }}.zip{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^refactor:'
      - '^style:'
      - '^ci:'
      - '^perf:'
      - '^build:'