// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"bg-[#232f3e] text-white p-4\"><div class=\"container mx-auto flex items-center justify-between\"><div class=\"flex items-center\"><span class=\"text-xl font-bold\">Lamba</span></div><div class=\"flex items-center space-x-4\"><button hx-get=\"/functions\" hx-target=\"#main-content\" class=\"px-4 py-2 hover:bg-gray-700 rounded transition-colors\">Functions</button> <button hx-get=\"/events\" hx-target=\"#main-content\" class=\"px-4 py-2 hover:bg-gray-700 rounded transition-colors\">Events</button> <button hx-get=\"/monitoring\" hx-target=\"#main-content\" class=\"px-4 py-2 hover:bg-gray-700 rounded transition-colors\">Monitoring</button></div><div class=\"flex items-center space-x-4\"><div class=\"relative\"><input type=\"text\" placeholder=\"Search functions\" class=\"bg-gray-700 text-white px-4 py-2 rounded w-64\"></div></div></div></nav><script>\n        function showCreateModal() {\n            document.getElementById('createFunctionModal').style.display = 'flex';\n        }\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
